LDI R0, #0
LDI R1, #0
LDI R2, #0
LDI R3, #0
LDI R4, #0
LDI R5, #0

CALL TEXT
CALL READ_INTEGER
MOV R1, R0
CALL TEXT
CALL READ_INTEGER
MOV R2, R0
ADD R1, R2
MOV R0, R1
CALL MODO_INTEGER_OUT
OUT
HLT

CALL MODO_CHAR_OUT
LDI R0, #13
OUT
LDI R0, #13
OUT
CALL TEXT
CALL READ_CHAR
OUT
HLT

CALL MODO_CHAR_OUT
LDI R0, #13
OUT
LDI R0, #13
OUT
CALL TEXT
CALL READ_CHAR_I
OUT

END

TEXT:
	CALL MODO_CHAR_OUT
	LDI R0, 'D'
	OUT
	LDI R0, 'I'
	OUT
	LDI R0, 'G'
	OUT
	LDI R0, 'I'
	OUT
	LDI R0, 'T'
	OUT
	LDI R0, 'E'
	OUT
	LDI R0, ':'
	OUT
	LDI R0, ' '
	OUT
	RET

;---------------------------------------------------------------------------------------------

MODO_CHAR_OUT:
	LDI R5, #1 ; CARREGA O VALOR DO MODO DE OUTPUT (char - modo 1)
	STA R5, &65534 ; INSERE O VALOR DO OUTPUT_MODE NA MEMORIA
	RET

MODO_INTEGER_OUT:
	LDI R5, #2 ; CARREGA O VALOR DO MODO DE OUTPUT (inteiro - modo 2)
	STA R5, &65534 ; INSERE O VALOR DO OUTPUT_MODE NA MEMORIA
	RET

;---------------------------------------------------------------------------------------------

MODO_CHAR_I:
	LDI R4, #1 ; CARREGA O VALOR DO MODO DE INPUT (char - modo 1)
	STA R4, &65533 ; INSERE O VALOR DO INPUT_MODE NA MEMORIA
	RET

MODO_CHAR:
	LDI R4, #2 ; CARREGA O VALOR DO MODO DE INPUT (char - modo 2)
	STA R4, &65533 ; INSERE O VALOR DO INPUT_MODE NA MEMORIA
	RET
	
MODO_INTEGER:
	LDI R4, #3 ; CARREGA O VALOR DO MODO DE INPUT (inteiro - modo 3)
	STA R4, &65533 ; INSERE O VALOR DO INPUT_MODE NA MEMORIA
	RET

;---------------------------------------------------------------------------------------------

READ_CHAR_I:
	CALL MODO_CHAR_I ; SETA O MODO DE INPUT PARA CARACTERE IMEDIATO
	LDA R3, &65531 ; CARREGA O DATA_STATE DE INPUT VERIFICANDO SE ESTA PRONTO
	CMP.I R3, #0
	BEQ.R #-7
	IN
	RET

READ_CHAR:
	CALL MODO_CHAR ; SETA O MODO DE INPUT PARA CARACTERE
	LDA R3, &65531 ; CARREGA O DATA_STATE DE INPUT VERIFICANDO SE ESTA PRONTO
	CMP.I R3, #0
	BEQ.R #-7
	IN
	RET
	
READ_INTEGER:
	CALL MODO_INTEGER ; SETA O MODO DE INPUT PARA INTEIRO
	LDA R3, &65531 ; CARREGA O DATA_STATE DE INPUT VERIFICANDO SE ESTA PRONTO
	CMP.I R3, #0
	BEQ.R #-7
	IN
	RET