LDI R0, #0
LDI R1, #0
LDI R2, #0
LDI R3, #0
LDI R4, #0
CALL TEXT ; TEXT 00100010
CALL READ_INTEGER ; READ 01000011
MOV R1, R0
CALL TEXT ; TEXT 00100010
CALL READ_INTEGER ; READ 01000011
MOV R2, R0
ADD R1, R2
MOV R0, R1
OUT
HLT
LDI R0, #13
DRAW
LDI R0, #13
DRAW
CALL TEXT
CALL READ_CHAR
DRAW
HLT
LDI R0, #13
DRAW
LDI R0, #13
DRAW
CALL TEXT
CALL READ_CHAR_I
DRAW
END

TEXT:
	LDI R0, 'D'
	DRAW
	LDI R0, 'I'
	DRAW
	LDI R0, 'G'
	DRAW
	LDI R0, 'I'
	DRAW
	LDI R0, 'T'
	DRAW
	LDI R0, 'E'
	DRAW
	LDI R0, ':'
	DRAW
	LDI R0, ' '
	DRAW
	RET

MODO_CHAR_I:
	LDI R4, #1 ; CARREGA O VALOR DO MODO DE INPUT (char - modo 1)
	STA R4, &65534 ; INSERE O VALOR DO MODO DE INPUT NA MEMORIA
	RET

MODO_CHAR:
	LDI R4, #2 ; CARREGA O VALOR DO MODO DE INPUT (char - modo 2)
	STA R4, &65534 ; INSERE O VALOR DO MODO DE INPUT NA MEMORIA
	RET
	
MODO_INTEGER:
	LDI R4, #3 ; CARREGA O VALOR DO MODO DE INPUT (inteiro - modo 3)
	STA R4, &65534 ; INSERE O VALOR DO MODO DE INPUT NA MEMORIA
	RET

READ_CHAR_I:
	;LDI R4, #1 ; CARREGA O VALOR DO MODO DE INPUT (char - modo 2)
	;STA R4, &65534 ; INSERE O VALOR DO MODO DE INPUT NA MEMORIA
	CALL MODO_CHAR_I
	LDA R3, &65532
	CMP.I R3, #0
	BEQ.R #-7
	IN
	RET

READ_CHAR:
	;LDI R4, #2 ; CARREGA O VALOR DO MODO DE INPUT (char - modo 2)
	;STA R4, &65534 ; INSERE O VALOR DO MODO DE INPUT NA MEMORIA
	CALL MODO_CHAR
	LDA R3, &65532
	CMP.I R3, #0
	BEQ.R #-7
	IN
	RET
	
READ_INTEGER:
	;LDI R4, #3 ; CARREGA O VALOR DO MODO DE INPUT (inteiro - modo 2)
	;STA R4, &65534 ; INSERE O VALOR DO MODO DE INPUT NA MEMORIA
	CALL MODO_INTEGER
	LDA R3, &65532
	CMP.I R3, #0
	BEQ.R #-7
	IN
	RET